### PR TITLE
Added SFSortingResults class

### PR DESCRIPTION
**Pull request by alejoe91**

### CODE REVIEW

**Comment by magland** [comment]
Thanks @alejoe91, could you please put this in a devel/ folder, and then I'll merge?

**Comment by alejoe91** [comment]
@magland it should be good to go! I added a notebook to show how to use the class

**Comment by magland** [comment]
@alejoe91 This looks great! One consideration: @jsoules and I recently adjusted the format of the sortings file - shouldn't be too big of a change, and your script might work as is. But we'll at least want to adjust the default URI.

See the updated example: https://github.com/flatironinstitute/spikeforest/blob/main/examples/load_spikeforest_sorting_outputs.py

As you can see, default URI is now: sha1://52f24579bb2af1557ce360ed5ccc68e480928285/file.txt?manifest=5bfb2b44045ac3e9bd2a8fe54ef67aa932844f58

If we update that and then verify that the notebook still works, then I will merge.

**Comment by magland** [comment]
I see you updated the uri. I'll merge, and if it doesn't work with the new file somehow, we'll fix it. Merging.

**Pull request merged**
